POST http://localhost:9001/user/register
Content-Type: application/json

{
    "name" : "rizky",
    "email" : "mmadrizky@gmail.com",
    "password" : "aezakmi"
}


POST http://localhost:9001/user/login
Content-Type: application/json

{
    "email" : "mmadrizky@gmail.com",
    "password" : "aezakmi"
}

# GET http://localhost:9001/user/history
# Content-Type: application/json
# Authorization: Bearer